/**
 * Nationalities offered in the intake form, ordered so the common cases at a
 * Thai outpatient department sit at the top before the alphabetical list.
 */
export const COMMON_NATIONALITIES = [
  "Thai",
  "Burmese",
  "Cambodian",
  "Lao",
  "Chinese",
  "Malaysian",
  "Vietnamese",
] as const;

export const OTHER_NATIONALITIES = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahraini",
  "Bangladeshi",
  "Belarusian",
  "Belgian",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Canadian",
  "Chilean",
  "Colombian",
  "Congolese",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Dutch",
  "Ecuadorian",
  "Egyptian",
  "Emirati",
  "Estonian",
  "Ethiopian",
  "Filipino",
  "Finnish",
  "French",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Korean",
  "Kuwaiti",
  "Kyrgyz",
  "Latvian",
  "Lebanese",
  "Libyan",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Maldivian",
  "Maltese",
  "Mexican",
  "Moldovan",
  "Mongolian",
  "Moroccan",
  "Nepali",
  "New Zealander",
  "Nigerian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palestinian",
  "Panamanian",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saudi",
  "Senegalese",
  "Serbian",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Somali",
  "South African",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Venezuelan",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
] as const;

export const NATIONALITIES: readonly string[] = [
  ...COMMON_NATIONALITIES,
  ...OTHER_NATIONALITIES,
];

export const DEFAULT_NATIONALITY = "Thai";
